# Site settings
name: LiZheng's Blog
email: lzmzzw@gmail.com
author: Li Zheng
url: http://www.lzmzzw.com
resume_site: http://www.lzmzzw.com/Resume.io/
github: https://github.com/lzmzzw/
baseurl: ""
description: Blog;Github Pages;jekyll
meta_description: Blog;Github Pages;jekyll
motto: Talk is cheap. Show me the code.

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lzmzzw

# Build settings
markdown: kramdown

baidu_analysis: bd230cffcc5be6dc17afd216048025aa

